/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import {
  useQuery
} from 'react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from 'react-query'
import type {
  GetSchools200
} from '.././model'
import { instance } from '.././instance';



/**
 * Get all schools
 */
export const getSchools = (
    
 signal?: AbortSignal
) => {
      
      
      return instance<GetSchools200>(
      {url: `/v0.0/schools/all`, method: 'GET', signal
    },
      );
    }
  

export const getGetSchoolsQueryKey = () => {
    return [`/v0.0/schools/all`] as const;
    }

    
export const getGetSchoolsQueryOptions = <TData = Awaited<ReturnType<typeof getSchools>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSchools>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSchoolsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchools>>> = ({ signal }) => getSchools(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSchools>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSchoolsQueryResult = NonNullable<Awaited<ReturnType<typeof getSchools>>>
export type GetSchoolsQueryError = unknown

export const useGetSchools = <TData = Awaited<ReturnType<typeof getSchools>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSchools>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetSchoolsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



