/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import {
  useQuery
} from 'react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from 'react-query'
import type {
  CheckMasterclassMatA200
} from '.././model'
import { instance } from '.././instance';



/**
 * Check if user has purchased of masterclass matA
 */
export const checkMasterclassMatA = (
    
 signal?: AbortSignal
) => {
      
      
      return instance<CheckMasterclassMatA200>(
      {url: `/v0.0/memberships/check/masterclass/matA`, method: 'GET', signal
    },
      );
    }
  

export const getCheckMasterclassMatAQueryKey = () => {
    return [`/v0.0/memberships/check/masterclass/matA`] as const;
    }

    
export const getCheckMasterclassMatAQueryOptions = <TData = Awaited<ReturnType<typeof checkMasterclassMatA>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof checkMasterclassMatA>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckMasterclassMatAQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkMasterclassMatA>>> = ({ signal }) => checkMasterclassMatA(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkMasterclassMatA>>, TError, TData> & { queryKey: QueryKey }
}

export type CheckMasterclassMatAQueryResult = NonNullable<Awaited<ReturnType<typeof checkMasterclassMatA>>>
export type CheckMasterclassMatAQueryError = unknown

export const useCheckMasterclassMatA = <TData = Awaited<ReturnType<typeof checkMasterclassMatA>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof checkMasterclassMatA>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getCheckMasterclassMatAQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



