/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { ChangeLastName200Data } from './changeLastName200Data';

export type ChangeLastName200 = {
  data: ChangeLastName200Data;
};
