/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { ChangeProfilePicture200Data } from './changeProfilePicture200Data';

export type ChangeProfilePicture200 = {
  data: ChangeProfilePicture200Data;
};
