/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { ChangeFirstName200Data } from './changeFirstName200Data';

export type ChangeFirstName200 = {
  data: ChangeFirstName200Data;
};
