/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { ChangeEmail200Data } from './changeEmail200Data';

export type ChangeEmail200 = {
  data: ChangeEmail200Data;
};
