/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { MasterClass } from './masterClass';

export type CheckMasterClassMembership200Data = {
  masterClass?: MasterClass;
  membershipUsersLogId?: number;
  startDate?: string;
};
