/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { Membership } from './membership';

export type CheckMasterclassMatA200 = {
  data: Membership;
};
