/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { CheckMasterClassMembership200Data } from './checkMasterClassMembership200Data';

export type CheckMasterClassMembership200 = {
  data?: CheckMasterClassMembership200Data;
};
