/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { ExamSubmissionDataGradeDistributionItem } from './examSubmissionDataGradeDistributionItem';

export type ExamSubmissionData = {
  createdAt?: string;
  criteriaPdf?: string;
  examId?: number;
  examName?: string;
  examPdf?: string;
  grade?: number;
  gradeDistribution?: ExamSubmissionDataGradeDistributionItem[];
  solutionPdf?: string;
  userAnswers?: string[];
};
