/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { ExamProfileTopicsItem } from './examProfileTopicsItem';

export interface ExamProfile {
  gradePrediction?: number;
  percentageCourseDone?: number;
  percentageExamsSubmited?: number;
  rankUser?: number;
  topics?: ExamProfileTopicsItem[];
  userProfileImage?: string;
}
