/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { ExamFeedbackDataGradeDistributionItem } from './examFeedbackDataGradeDistributionItem';

export type ExamFeedbackData = {
  criteriaPdf?: string;
  examId?: number;
  examName?: string;
  examPdf?: string;
  grade?: number;
  gradeDistribution?: ExamFeedbackDataGradeDistributionItem[];
  solutionPdf?: string;
};
