/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */

export type ExamFeedbackGradeDistributionItem = {
  numberCorrectExercises?: number;
  numberIncorrectExercises?: number;
  numberTotalExercises?: number;
  subTopicId?: number;
  subTopicName?: string;
};
