/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { ExerciseSubTopicTopicSchoolYear } from './exerciseSubTopicTopicSchoolYear';
import type { ExerciseSubTopicTopicSubject } from './exerciseSubTopicTopicSubject';

export type ExerciseSubTopicTopic = {
  name: string;
  schoolYear: ExerciseSubTopicTopicSchoolYear;
  subject: ExerciseSubTopicTopicSubject;
  topicId: number;
};
