/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { CourseTopic } from './courseTopic';

export type GetCourseTopics200Data = {
  courseTopicDTOs: CourseTopic[];
  overallPercentage: number;
};
