/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { GetExercises200DataExercises } from './getExercises200DataExercises';

export type GetExercises200Data = {
  exercises: GetExercises200DataExercises;
  notesUrl: string;
};
