/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { GetExercisesAndUrl200Data } from './getExercisesAndUrl200Data';

export type GetExercisesAndUrl200 = {
  data: GetExercisesAndUrl200Data;
};
