/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { GetExercisesAndUrl200DataExercises } from './getExercisesAndUrl200DataExercises';

export type GetExercisesAndUrl200Data = {
  exercises: GetExercisesAndUrl200DataExercises;
  notesUrl: string;
};
