/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { GetGraphData200Data } from './getGraphData200Data';

export type GetGraphData200 = {
  data: GetGraphData200Data;
};
