/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { GetGraphData200DataExercisesDonePerDayItem } from './getGraphData200DataExercisesDonePerDayItem';

export type GetGraphData200Data = {
  exercisesDonePerDay?: GetGraphData200DataExercisesDonePerDayItem[];
};
