/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { GetProfileStats200Data } from './getProfileStats200Data';

export type GetProfileStats200 = {
  data?: GetProfileStats200Data;
};
