/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { GetTestGraphData200DataExercisesDonePerDayItem } from './getTestGraphData200DataExercisesDonePerDayItem';

export type GetTestGraphData200Data = {
  exercisesDonePerDay?: GetTestGraphData200DataExercisesDonePerDayItem[];
};
