/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */

export type MembershipMasterclassMembershipPaymentTypesItem = {
  amount?: number;
  duration?: number;
  membershipPaymentTypeId?: number;
  name?: string;
};
