/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { RegisterBodyGradeYearDistributionsItem } from './registerBodyGradeYearDistributionsItem';

export type RegisterBody = {
  currentSchoolYearId: number;
  firebaseUserId: string;
  firstName: string;
  gradeYearDistributions?: RegisterBodyGradeYearDistributionsItem[];
  lastName: string;
  partnerName: string;
  schoolId: number;
  selfAssesment: number;
  userName: string;
};
