/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { TestFeedbackGradeDistributionItem } from './testFeedbackGradeDistributionItem';

export interface TestFeedback {
  createdAt?: string;
  grade?: number;
  gradeDistribution?: TestFeedbackGradeDistributionItem[];
  submissionId?: number;
  timeElapsed?: number;
  userAnswers?: string[];
}
