/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { TestSubTopicsItemSubTopic } from './testSubTopicsItemSubTopic';

export type TestSubTopicsItem = {
  percentage?: number;
  subTopic?: TestSubTopicsItemSubTopic;
  testEventSubTopicId?: number;
};
