/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { TestInfoExercisesItemSubTopicTopicSchoolYear } from './testInfoExercisesItemSubTopicTopicSchoolYear';
import type { TestInfoExercisesItemSubTopicTopicSubject } from './testInfoExercisesItemSubTopicTopicSubject';

export type TestInfoExercisesItemSubTopicTopic = {
  name?: string;
  schoolYear?: TestInfoExercisesItemSubTopicTopicSchoolYear;
  subject?: TestInfoExercisesItemSubTopicTopicSubject;
  topicId?: number;
};
