/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import type { UserInfo } from './userInfo';

export interface UserInfoWithCorrectAnswers {
  totalCorrectAnswers: number;
  user: UserInfo;
}
