/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * student-hub-api
 * Api Documentation for StudentHub API
 * OpenAPI spec version: 0.0
 */
import {
  useMutation
} from 'react-query'
import type {
  MutationFunction,
  UseMutationOptions
} from 'react-query'
import type {
  GetStreaks200
} from '.././model'
import { instance } from '.././instance';



/**
 * Get user daily streak
 */
export const getStreaks = (
    
 ) => {
      
      
      return instance<GetStreaks200>(
      {url: `/v0.0/streaks/user`, method: 'POST'
    },
      );
    }
  


export const getGetStreaksMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getStreaks>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getStreaks>>, TError,void, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getStreaks>>, void> = () => {
          

          return  getStreaks()
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type GetStreaksMutationResult = NonNullable<Awaited<ReturnType<typeof getStreaks>>>
    
    export type GetStreaksMutationError = unknown

    export const useGetStreaks = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getStreaks>>, TError,void, TContext>, }
) => {

      const mutationOptions = getGetStreaksMutationOptions(options);

      return useMutation(mutationOptions);
    }
    